name: CSCLEDE-Lenovo_Newifi-Y1Y1S
on: 
  push:
    branches: 
      - master
  release:
    types: [published]
  schedule:
    - cron: 20 20 5,15,25 * *
  #watch:
  #  types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        # sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        # sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        # sudo -E apt-get -y autoremove --purge
        # sudo -E apt-get clean
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
    - name: Clone custom source code
      run: |
        cd openwrt/package
        mkdir coolsong
        cd coolsong
        git clone https://github.com/tty228/luci-app-serverchan.git
        git clone https://github.com/tzxiaozhen88/luci-app-koolproxyR.git
        git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
        git clone https://github.com/happyzhang1995/openwrt-adguardhome.git
        git clone https://github.com/wubin2/luci-theme-argon.git
        git clone https://github.com/vernesong/OpenClash.git
        mv OpenClash/luci-app-openclash ./luci-app-openclash
        rm -rf OpenClash
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
    - name: Configuration Customization - Build_Lenovo_Newifi-Y1Y1S
      env:
        CONFIG_FILE: 'lenovo_newifi-y1y1s.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
    #- name: SSH connection to Actions
    #  uses: wubin2/AutoBuild-CSCLEDE@master
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: CSCLEDE-Lenovo_Newifi-Y1Y1S
        path: openwrt/bin
